### ISSUE TITLE
Lawnchair.js to circumvent hard 5MB localStorage cap

### ISSUE THREAD

**Issue by rtfeldman** [awwx/meteor-browser-store#1]
I'm interested in meteor-browser-store for performance reasons: we have a large collection that unavoidably needs to be synced with the client. This results in several seconds of page load time, which I am fairly desperate to alleviate.

Local persistence seems like a great solution, as then just the latest updates would need to be synced on page load. Unfortunately, localStorage has a hard cap of 5MB in Chrome, which this collection will gobble up in short order.

It seems like Lawnchair.js - http://brian.io/lawnchair/ - could solve this, as it provides a localStorage-like JSON API that wraps several storage solutions, including IndexedDB (which is not capped).

Thoughts?

**Comment by awwx** [comment]
Did you see https://github.com/awwx/meteor-browser-collection#readme ?  It's not as far along as browser-store, but it's designed to persist collections.
